name: brickdance
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^2.4.1
  go_router: ^14.0.0
  json_annotation: ^4.9.0
  slang_flutter: ">=4.0.0 <4.11.0" # error in version 4.11.0
  slang: ">=4.0.0 <4.11.0" # error in version 4.11.0
  snowflake_flutter_theme:
    git:
      url: https://github.com/icodeyou/snowflake_flutter_theme
      ref: v27
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  slang_build_runner: ">=4.0.0 <4.11.0" # error in version 4.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
